# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKZEY6zMghJMGPa9h9-eVjLaXNqGlAXe
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Weather Prediction App",
    page_icon="🌦️",
    layout="wide"
)

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_files():
    model = pickle.load(open("weather_model.pkl", "rb"))
    scaler = pickle.load(open("scaler.pkl", "rb"))
    columns = pickle.load(open("columns.pkl", "rb"))
    return model, scaler, columns

model, scaler, columns = load_files()

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
.main {
    background: linear-gradient(to right, #dfe9f3, #ffffff);
}

.title {
    text-align: center;
    font-size: 45px;
    font-weight: bold;
    color: #0f172a;
}

.sub {
    text-align: center;
    color: gray;
    font-size: 18px;
}

.card {
    background: white;
    padding: 25px;
    border-radius: 20px;
    box-shadow: 0px 4px 20px rgba(0,0,0,0.1);
    margin-bottom: 20px;
}

.result {
    text-align: center;
    font-size: 30px;
    font-weight: bold;
}
</style>
""", unsafe_allow_html=True)

# ---------------- HEADER ----------------
st.markdown("<div class='title'>🌦️ Weather Rain Prediction</div>", unsafe_allow_html=True)
st.markdown("<div class='sub'>Predict whether it will rain tomorrow</div>", unsafe_allow_html=True)

# ---------------- SIDEBAR INPUT ----------------
st.sidebar.header("Enter Weather Details")

MinTemp = st.sidebar.slider("Min Temp", -10.0, 40.0, 15.0)
MaxTemp = st.sidebar.slider("Max Temp", 0.0, 50.0, 25.0)
Rainfall = st.sidebar.slider("Rainfall", 0.0, 100.0, 5.0)
Evaporation = st.sidebar.slider("Evaporation", 0.0, 20.0, 5.0)
Sunshine = st.sidebar.slider("Sunshine", 0.0, 15.0, 7.0)
WindGustSpeed = st.sidebar.slider("Wind Gust Speed", 0.0, 150.0, 50.0)
Humidity9am = st.sidebar.slider("Humidity 9am", 0, 100, 60)
Humidity3pm = st.sidebar.slider("Humidity 3pm", 0, 100, 50)
Pressure9am = st.sidebar.slider("Pressure 9am", 900.0, 1100.0, 1010.0)
Pressure3pm = st.sidebar.slider("Pressure 3pm", 900.0, 1100.0, 1012.0)
Temp9am = st.sidebar.slider("Temp 9am", -10.0, 40.0, 18.0)
Temp3pm = st.sidebar.slider("Temp 3pm", -10.0, 50.0, 24.0)

# ---------------- INPUT DATA ----------------
input_dict = {
    "MinTemp": MinTemp,
    "MaxTemp": MaxTemp,
    "Rainfall": Rainfall,
    "Evaporation": Evaporation,
    "Sunshine": Sunshine,
    "WindGustSpeed": WindGustSpeed,
    "Humidity9am": Humidity9am,
    "Humidity3pm": Humidity3pm,
    "Pressure9am": Pressure9am,
    "Pressure3pm": Pressure3pm,
    "Temp9am": Temp9am,
    "Temp3pm": Temp3pm,
}

input_df = pd.DataFrame([input_dict])

# Match training columns
for col in columns:
    if col not in input_df.columns:
        input_df[col] = 0

input_df = input_df[columns]

# Scale
scaled_input = scaler.transform(input_df)

# ---------------- MAIN AREA ----------------
col1, col2 = st.columns([2, 1])

with col1:
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("📊 Input Weather Data")
    st.dataframe(input_df)
    st.markdown("</div>", unsafe_allow_html=True)

with col2:
    st.markdown("<div class='card'>", unsafe_allow_html=True)

    if st.button("🔍 Predict Rain"):
        prediction = model.predict(scaled_input)[0]
        probability = model.predict_proba(scaled_input)[0][1]

        if prediction == 1:
            st.success("🌧️ Rain Expected Tomorrow")
        else:
            st.info("☀️ No Rain Tomorrow")

        st.progress(float(probability))
        st.write(f"Confidence Score: **{probability:.2%}**")

    st.markdown("</div>", unsafe_allow_html=True)
