# -*- coding: utf-8 -*-
"""MLproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGjZJJLW5SA5fQq6TdiryxsRL-2sXs8A
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

df = pd.read_csv("weatherAUS.csv")

df

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

df.duplicated().sum()

corr = df.corr(numeric_only=True)

print(corr)

"""df.median(numeric_only=True) → બધા numerical columns નો median કાઢે છે
fillna(...) → તે median થી null values ભરે છે
inplace=True → original DataFrame માં જ change થાય છે

👉 એટલે આ line numeric columns ના null values ને median થી ભરે છે
"""

df.fillna(df.median(numeric_only=True), inplace=True)
df.fillna("Unknown", inplace=True)

"""numeric values fill કર્યા પછી હજુ પણ string / categorical columns માં null હોઈ શકે
આ line એ બધા remaining null values ને "Unknown" થી ભરે છે
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.show()

sns.countplot(x="RainTomorrow", data=df)
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df["MinTemp"])
plt.title("Box Plot of MinTemp")
plt.show()

X = df.drop("RainTomorrow", axis=1)
y = df["RainTomorrow"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix

print( accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

print("Logistic:", accuracy_score(y_test, model.predict(X_test)))

pickle.dump(model, open("weather_model.pkl", "wb"))

pickle.dump(scaler, open("scaler.pkl", "wb"))

pickle.dump(X.columns.tolist(), open("columns.pkl", "wb"))

pickle.dump(le,open("label_encoder.pkl", "wb"))

